// stories/svelte/src/ShowBasic.svelte
<script lang="ts">
	import ShowBasicContent from './views/ShowBasicContent.svelte'
	import StoryShell from './components/StoryShell.svelte'
	import { DEFAULT_POST_ID } from '@ginjou/storybook-shared/mock-data'
</script>

<StoryShell
	routes={{ '/posts/:id': ShowBasicContent }}
	initialPath={`/posts/${DEFAULT_POST_ID}`}
/>

// stories/vue/src/ShowBasic.vue
<script setup lang="ts">
import type { Post } from '@ginjou/storybook-shared/mock-data'
import { useShow } from '@ginjou/vue'
import JsonOutput from './components/JsonOutput.vue'
import LocaleBadge from './components/LocaleBadge.vue'
import PageTitle from './components/PageTitle.vue'
import Stack from './components/Stack.vue'
import StoryShell from './components/StoryShell.vue'

const { record } = useShow<Post>()
</script>

<template>
	<StoryShell>
		<Stack>
			<LocaleBadge />
			<PageTitle>Posts Details</PageTitle>

			<JsonOutput :value="record" />
		</Stack>
	</StoryShell>
</template>
